apiVersion: v1
kind: Pod
metadata:
  name: nosqlmark-client
  namespace: foxtrot-rebalance-20260911-055959
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: i-063b793db694be24c
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels: {cluster: "redis-20260911-055959", component: redis}
        topologyKey: kubernetes.io/hostname
  containers:
  - name: client
    image: maven:3.8.7-eclipse-temurin-8
    command: [sleep, infinity]
    resources:
      requests: {cpu: "1", memory: 2Gi}
      limits: {cpu: "2", memory: 4Gi}
